#!/bin/sh

num=$(git diff-index --name-only --diff-filter=ACMR HEAD -- | grep '.md$' | wc -l)
if [ $num -gt 1 ]
then
  echo >&2 Too many Markdown files.
  exit 1
fi

fs=$(git diff-index --name-only --diff-filter=ACMR HEAD -- | grep '.md$')

if [ $fs == "README.md" ]
then
  exit 0
fi

if [ -n $fs ]
then
    til=$(cat ${fs} | head -1 | awk '{split($0,a," ");print a[2]}')
    msg=$(egrep "^$til v[0-9]+(\.[0-9]+)*" "$1")
    test -n "$msg" || {
      echo >&2 Invalid commit message.
      exit 1
    }
fi

